// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_algorithms_algorithm_ from "./routes/api/algorithms/[algorithm].ts";
import * as $api_algorithms_graph from "./routes/api/algorithms/graph.ts";
import * as $api_algorithms_searching from "./routes/api/algorithms/searching.ts";
import * as $api_algorithms_sorting from "./routes/api/algorithms/sorting.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MainContent from "./islands/MainContent.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/algorithms/[algorithm].ts": $api_algorithms_algorithm_,
    "./routes/api/algorithms/graph.ts": $api_algorithms_graph,
    "./routes/api/algorithms/searching.ts": $api_algorithms_searching,
    "./routes/api/algorithms/sorting.ts": $api_algorithms_sorting,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/MainContent.tsx": $MainContent,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
